# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTdIP60WZVDpbiA7R7rdw_ooAbI1bU4S

# Loading the frameworks and dataset into notebook
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

#reading from csv
df=pd.read_csv("Mall_Customers.csv")

#showing data(5 rows)
df.head()

#information about data base
df.info()

#checking for null values
df.isnull()

"""# EDA(Exploratory data analysis)"""

#to find out mean income with respect to age
df.groupby('Age')['Annual Income (k$)'].mean()

"""Age 41 income is highest"""

sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')

"""Conclusion from the above figure:No Lines in the heatmap so it means that there is no null value.No missing value treatment is required"""

sns.countplot(x=df['Gender'],data=df)

"""From the above figure No of females is higher than male"""

#Now plotting the age-distribution of the data-set

plt.hist(df['Age'])
plt.xlabel("AGE")
plt.ylabel("Frequency")

"""Conclusion from the above graph: This histogram is right skewed which shows that the older people are visiting less in number."""

#now creating age distributions for male
plt.hist('Age', data=df[df['Gender'] == 'Male'])

"""So younger age are visiting mall more than older ones."""

#now creating age distributions for female
plt.hist('Age',data=df[df['Gender']=='Female'])

"""Middle age females are visiting mall more than the others."""

#boxplot of anual income with respect to gender to see percentile value
sns.boxplot('Gender','Annual Income (k$)', data=df)

"""One outlier in male,50 percentile value is nearly 62K dollar for male. For female it is nearly 59K dollar."""

#boxplot of spending score with respect to gender to see percentile value
sns.boxplot('Gender','Spending Score (1-100)', data=df)

"""from the above boxplot it can be focused that male 50th percentile spending score is 50K dollar and female is also nearly same 50K dollar"""

#Histogram to show relation between age and no of customers
age18_25 = df.Age[(df.Age <= 25) & (df.Age >= 18)]
age26_35 = df.Age[(df.Age <= 35) & (df.Age >= 26)]
age36_45 = df.Age[(df.Age <= 45) & (df.Age >= 36)]
age46_55 = df.Age[(df.Age <= 55) & (df.Age >= 46)]
age55above = df.Age[df.Age >= 56]

x = ["18-25","26-35","36-45","46-55","55+"]
y = [len(age18_25.values),len(age26_35.values),len(age36_45.values),len(age46_55.values),len(age55above.values)]

plt.figure(figsize=(15,6))
sns.barplot(x=x, y=y, palette="rocket")
plt.title("Number of Customer and Ages")
plt.xlabel("Age")
plt.ylabel("Number of Customer")

"""conclusion:(26-35) aged people are visiting  mall more frequently."""

#Histogram to show spending score and number of customers
ss1_20 = df["Spending Score (1-100)"][(df["Spending Score (1-100)"] >= 1) & (df["Spending Score (1-100)"] <= 20)]
ss21_40 = df["Spending Score (1-100)"][(df["Spending Score (1-100)"] >= 21) & (df["Spending Score (1-100)"] <= 40)]
ss41_60 = df["Spending Score (1-100)"][(df["Spending Score (1-100)"] >= 41) & (df["Spending Score (1-100)"] <= 60)]
ss61_80 = df["Spending Score (1-100)"][(df["Spending Score (1-100)"] >= 61) & (df["Spending Score (1-100)"] <= 80)]
ss81_100 = df["Spending Score (1-100)"][(df["Spending Score (1-100)"] >= 81) & (df["Spending Score (1-100)"] <= 100)]

ssx = ["1-20", "21-40", "41-60", "61-80", "81-100"]
ssy = [len(ss1_20.values), len(ss21_40.values), len(ss41_60.values), len(ss61_80.values), len(ss81_100.values)]

plt.figure(figsize=(15,6))
sns.barplot(x=ssx, y=ssy, palette="nipy_spectral_r")
plt.title("Spending Scores")
plt.xlabel("Score")
plt.ylabel("Number of Customer Having the Score")

"""Conclusion from the above fig: People having spending score of 41-50 are more in our dataset."""

#Histogram to show Annual income and no of customers
ai0_30 = df["Annual Income (k$)"][(df["Annual Income (k$)"] >= 0) & (df["Annual Income (k$)"] <= 30)]
ai31_60 = df["Annual Income (k$)"][(df["Annual Income (k$)"] >= 31) & (df["Annual Income (k$)"] <= 60)]
ai61_90 = df["Annual Income (k$)"][(df["Annual Income (k$)"] >= 61) & (df["Annual Income (k$)"] <= 90)]
ai91_120 = df["Annual Income (k$)"][(df["Annual Income (k$)"] >= 91) & (df["Annual Income (k$)"] <= 120)]
ai121_150 = df["Annual Income (k$)"][(df["Annual Income (k$)"] >= 121) & (df["Annual Income (k$)"] <= 150)]

aix = ["$ 0 - 30,000", "$ 30,001 - 60,000", "$ 60,001 - 90,000", "$ 90,001 - 120,000", "$ 120,001 - 150,000"]
aiy = [len(ai0_30.values), len(ai31_60.values), len(ai61_90.values), len(ai91_120.values), len(ai121_150.values)]

plt.figure(figsize=(15,6))
sns.barplot(x=aix, y=aiy, palette="Set2")
plt.title("Annual Incomes")
plt.xlabel("Income")
plt.ylabel("Number of Customer")

"""from the above histogram:60K-90K dollar is the income of most people.

# Feature selection part

# As per the question we have to plot between annual income and spending scores, so these two features are  selected from the dataset.
"""

#view the corelation between the data
df.corr()

#Many of them have negative co relation
sns.heatmap(df.corr())

#scaterplot of spending score and annual income
sns.scatterplot('Annual Income (k$)', 'Spending Score (1-100)', hue='Gender', data=df);
plt.title('Annual Income v/s Spending Score, Colored by Gender');

"""From the scaterplot we can come on a conclusion that there are 5 clusters"""

#including Kmeans algorithm from sklearn and run for a random 1 to 15 clusters
from sklearn.cluster import KMeans



x=[]
for i in range(1,15):
    kmeans=KMeans(n_clusters=i,random_state=101)
    kmeans.fit(df.iloc[:,3:])
    x.append(kmeans.inertia_)

plt.plot(range(1,15),x,'bx-')
plt.xlabel('Values of K')
plt.ylabel('Distortions')
plt.title('The elbow method using Distortion')

"""From Elbow method and the scaterplot we can come on a conclusion that number of clusters on the data is 5"""

#running k mean clustering algorithm
X=df.iloc[:,[3,4]].values
kmeans=KMeans(n_clusters=5,init='k-means++',random_state=0)
y_kmeans=kmeans.fit_predict(X)

#Centroids of the clusters 
kmeans.cluster_centers_

kmeans.labels_

#plotting the clusters in plot and sho the different clusters with their centroids
f,ax=plt.subplots(1,1,sharey=True,figsize=(10,6))
ax.scatter(X[y_kmeans==0,0],X[y_kmeans==0,1],c='red',label='Cluster1')
ax.scatter(X[y_kmeans==1,0],X[y_kmeans==1,1],c='blue',label='Cluster2')
ax.scatter(X[y_kmeans==2,0],X[y_kmeans==2,1],c='black',label='Cluster3')
ax.scatter(X[y_kmeans==3,0],X[y_kmeans==3,1],c='cyan',label='Cluster4')
ax.scatter(X[y_kmeans==4,0],X[y_kmeans==4,1],c='magenta',label='Cluster5')

ax.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],c='yellow',label='Centroids')

plt.title('Clusters of customers')
plt.xlabel('Annual Income(K$)')
plt.ylabel('Spending Score(1-100)')
plt.legend()

"""Cluster 1: Average income and average spending

Cluster 2:Minimum income but high spending

Cluster 3:High income and high spending

Cluster 4:Low inclome and Low spending

Cluster 5:High income but low spending
"""

